name: py37
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==23.1.0
    - beir==1.0.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - datasets==2.12.0
    - dill==0.3.6
    - elasticsearch==7.9.1
    - faiss-cpu==1.7.4
    - filelock==3.12.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - huggingface-hub==0.14.1
    - idna==3.4
    - importlib-metadata==6.6.0
    - joblib==1.2.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nltk==3.8.1
    - numpy==1.21.6
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - packaging==23.1
    - pandas==1.3.5
    - pillow==9.5.0
    - pyarrow==12.0.0
    - python-dateutil==2.8.2
    - pytrec-eval==0.5
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.5.5
    - requests==2.30.0
    - responses==0.18.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - six==1.16.0
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - torch==1.13.1
    - torchvision==0.14.1
    - tqdm==4.65.0
    - transformers==4.29.2
    - typing-extensions==4.5.0
    - urllib3==2.0.2
    - xxhash==3.2.0
    - yarl==1.9.2
    - zipp==3.15.0
